### ISSUE TITLE
macOS 10.14.5 - impossible to import 

### ISSUE THREAD

**Issue by bezvoshchuk** [arcticicestudio/nord-terminal-app#6]
Hi Community! 
Tryin' to setup new laptop, on the latest macOS i can't import the theme.

Tryin' to import theme "open"-button is disabled:
<img width="806" alt="Screenshot 2019-06-28 at 11 46 59" src="https://user-images.githubusercontent.com/5589372/60334525-ffacb500-999b-11e9-8a61-5beb59430020.png">

Tryin' to open Nord.terminal file I have an error:
<img width="422" alt="Screenshot 2019-06-28 at 11 47 30" src="https://user-images.githubusercontent.com/5589372/60334592-308cea00-999c-11e9-8363-70cc5e63ea9c.png">

Could you please help me with this?

**Comment by arcticicestudio** [comment]
Hi @d1monster, have you donwloaded the file manually or cloned the repository? Maybe the file got corrupted (package loss, error while stitching the downloaded fragments etc.). "Luckily" I haven't updated to the latest maOS version yet so I tried to reproduce the problem, but it works fine for both methods either by using the installation steps described in the README as well as simply trying to open the file.

![gh-6-system_info](https://user-images.githubusercontent.com/7836623/61325839-d9996880-a815-11e9-815b-207be4b6e414.png)

![gh-6-import](https://user-images.githubusercontent.com/7836623/61325845-dd2cef80-a815-11e9-8661-c76bba43247d.png)

<img width="779" alt="gh-6-imported_profile" src="https://user-images.githubusercontent.com/7836623/61325853-df8f4980-a815-11e9-887b-5d7106477266.png">

Is the problem still reproducible when cloning the repository and importing the file afterwards?

**Comment by bezvoshchuk** [comment]
Hello @arcticicestudio,
Thanks for your reply! 
Happy to let you know that after cloning of repo import of theme works 👍
What also works and what I did previously - I exported theme form my colleague. In this case import was available. 
But with direct downloading of the file (I tried several laptops, but always latest macOS and latest Chrome or Safari) the import is just inactive and opening the file with Terminal app produce an error.

**Comment by arcticicestudio** [comment]
Glad to see it works for you now :smile: 
I'll take at the manual download, maybe there are some encoding problems since in the end it is just a simple XML file.
