### ISSUE TITLE
Command line tool used in screenshot

### ISSUE THREAD

**Issue by tomassliz** [arcticicestudio/nord-terminal-app#8]
May I ask you what is the command line tool you're using in screenshots? I tried to find it in all other repositories or on your Nord website but in vain. Thanks a lot!

**Comment by arcticicestudio** [comment]
Hi @tomassliz, this is a script I've found many years ago that is also included in the [color scripts repository](https://github.com/stark/Color-Scripts).

**Comment by tomassliz** [comment]
Awesome, thanks a lot!
